# Generated by Django 6.0.3 on 2026-03-20 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название предприятия')),
                ('business_type', models.CharField(choices=[('retail', 'Розничная торговля'), ('wholesale', 'Оптовая торговля'), ('manufacturing', 'Производство'), ('services', 'Услуги'), ('cafe', 'Кафе/Ресторан'), ('other', 'Другое')], max_length=50, verbose_name='Сфера деятельности')),
                ('description', models.TextField(blank=True, verbose_name='Описание деятельности')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('employees_count', models.IntegerField(default=1, verbose_name='Количество сотрудников')),
                ('need_1c_buh', models.BooleanField(default=False, verbose_name='Нужна 1С:Бухгалтерия')),
                ('need_1c_trade', models.BooleanField(default=False, verbose_name='Нужна 1С:Управление торговлей')),
                ('need_1c_salary', models.BooleanField(default=False, verbose_name='Нужна 1С:Зарплата и кадры')),
                ('need_cloud', models.BooleanField(default=False, verbose_name='Интересует облачная версия')),
                ('comment', models.TextField(blank=True, verbose_name='Дополнительный комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('in_work', 'В работе'), ('completed', 'Подключено'), ('rejected', 'Отказано')], default='pending', max_length=20, verbose_name='Статус')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Заявка на дистрибутив',
                'verbose_name_plural': 'Заявки на дистрибутив',
                'ordering': ['-created_at'],
            },
        ),
    ]
