# Generated by Django 6.0.3 on 2026-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_distributionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('description', models.TextField(verbose_name='Описание программы')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сервиса')),
                ('description', models.TextField(verbose_name='Описание сервиса')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='distributionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_work', 'В работе'), ('completed', 'Подключено'), ('rejected', 'Отказано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
