# Generated by Django 6.0.3 on 2026-04-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_servicecategory_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='short_description',
        ),
    ]
