# Generated by Django 6.0.3 on 2026-04-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_remove_license_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='image',
            field=models.ImageField(blank=True, default='slug.png', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
