# Generated by Django 6.0.3 on 2026-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_license_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
